language: scala
scala:
  - 2.11.2
jdk:
  - oraclejdk8
before_install:
  sudo pip install codecov
script: "sbt clean scoverage:test"
notifications:
  email: false
after_success:
  codecov
deploy:
  provider: heroku
  api-key:
    secure: aA4ZLzIuXqSBS8gnxLoUeps403Q6gzt1w8mcYmJlnPVArfHObnZxO3Kvf49yKHvIEmRgwuFbXfFzUwfr8rlQC59bbuKMZmsH6MKWTSsHJ87ZqclhyWEcxJkhfH5LxUWEkhVuwHtkGta7i558+Y7IB+x8Ukyt37QbFpu+0YkHZRo=

